---
- hosts: all
  become: yes
  tasks:
  - jenkins_job:
      config: "{{ lookup('file', 'templates/pom.xml') }}"
      name: test
      password: raj
      state: present
      url: http://34.224.6.141:8080/
      user: raj